### PR TITLE
Feature/pro 207 video carousel

### PR DESCRIPTION
**Pull request by MGrudule**
image

TODO:
- once API returns Cloudflare URL with video code, repace the placeholder video with the src
- decide if GIF or JPG video poster 
- decide if next/prev buttons should be hidden on desktop view

### CODE REVIEW

**Comment by smakhtin** [comment]
@MGrudule 

**UX:**
Strange glow here:
image

Also, maybe let's use standard green colour for control elements? Same as we used for audio player?

**Comment by smakhtin** [comment]
@MGrudule Video button is not clickable first time when it switches from image to video:
button is not clickable

**Comment by smakhtin** [comment]
URL of the video is not dynamically fetches from API.

**Comment by MGrudule** [comment]
image
image

- chnaged theme to match the audio player
- removed strange glow
- fixed the issue with play being unclickable after navigation
- fixed mobile button states

**Pull request merged**
